### ISSUE TITLE
How to solve this problem in isaacgym version 4？

### ISSUE THREAD

**Issue by xiaobai0906** [j3soon/OmniIsaacGymEnvs-UR10Reacher#1]
AttributeError: 'isaacgym._bindings.linux-x86_64.gym_37.Gym' object has no attribute 'create_force_sensor'

**Comment by j3soon** [comment]
Please note that this project uses Omniverse Isaac Gym, instead of Isaac Gym (Preview 1-4).

**Comment by xiaobai0906** [comment]
thank you




王佑谦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "j3soon/OmniIsaacGymEnvs-UR10Reacher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [j3soon/OmniIsaacGymEnvs-UR10Reacher] How to solve this problem in isaacgym version 4？ (Issue #1)





 
Please note that this project uses Omniverse Isaac Gym, instead of Isaac Gym (Preview 1-4).
